#title: Muhamad Naim bin Zol
#title: Muhamad Naim bin Zol
# description: Muhamad Naim bin Zol, a mechanical engineering graduate with expertise in Python, data visualization, machine learning, image processing and statistics.

description: |
  A mechanical engineering graduate with expertise in Python, data visualization, machine learning, image processing, and statistics.
  Data Science Professional Certificate, Universiti Sains Malaysia
  Bachelor in Mechanical Engineering, Korea University


theme: jekyll-theme-cayman
