#title: Muhamad Naim bin Zol
title: Muhamad Naim bin Zol
description: Muhamad Naim bin Zol, mechanical engineering graduate with expertise in Python, data visualization, machine learning, image processing and statistics.
theme: jekyll-theme-cayman
